# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_auto_20171113_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prix', models.CharField(max_length=200)),
                ('shippingCost', models.CharField(max_length=200)),
                ('shippingVolume', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('location', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shippingCost',
            field=models.CharField(default='0', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='shippingVolume',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stockVolume',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='stock',
            field=models.ManyToManyField(to='boutique.Product'),
        ),
        migrations.AddField(
            model_name='box',
            name='products',
            field=models.ManyToManyField(to='boutique.Product'),
        ),
    ]
