# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0007_auto_20171116_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('divId', models.CharField(max_length=200)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.SiteImage')),
            ],
        ),
    ]
