# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0010_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='bgdark',
            field=models.CharField(default=11445, max_length=200),
            preserve_default=False,
        ),
    ]
