# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0011_theme_bgdark'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='btnprimary',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='btnprimaryhover',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='btnprimarytextcolor',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='btnsecondary',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='btnsecondaryhover',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='btnsecondarytextcolor',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
